/*#define LEFT_RIGHT 0;
#define RIGHT_LEFT 1;
#define UP_DOWN 2;
#define DOWN_UP 3;
#define UPLEFT_DOWNRIGHT 4;
#define DOWNRIGHT_UPLEFT 5;
#define DOWNLEFT_UPRIGHT 6;
#define UPRIGHT_DOWNLEFT 7;*/

enum typeSO {LEFT_RIGHT, RIGHT_LEFT, UP_DOWN, DOWN_UP, UPLEFT_DOWNRIGHT, DOWNRIGHT_UPLEFT, DOWNLEFT_UPRIGHT, UPRIGHT_DOWNLEFT};